import type { Metadata } from "next";
import "../globals.css";
import DockComponent from "@/components/DockComponent";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      {children}
      <div className="max-h-14 fixed bottom-2 left-1/2 transform -translate-x-1/2 z-50 flex justify-center items-center w-full p-4">
        <DockComponent />
      </div>
    </>
  );
}
