import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import ClientProvider from "@/components/ClientProvider";
import { UserProvider } from "@/contexts/UserContext";
import DockComponent from "@/components/DockComponent";
import { Toaster } from "@/components/ui/toaster";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const queryClient = new QueryClient();
  return (
    <html lang="es">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >        
          <UserProvider>

        <ClientProvider>
          {children}
          <div className="max-h-14 fixed bottom-2 left-1/2 transform -translate-x-1/2 z-50 flex justify-center items-center w-full p-4">
            <DockComponent/>
          </div>
          </ClientProvider>
        </UserProvider>
      </body>
    </html>
  );
}
